[package]
name = "function_widget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.23.0"
ordered_hash_map = "0.4.0"
runnable = { path = "../runnable" }
